default: &default
  adapter: postgresql
  encoding: unicode
  username: rey
  password: tuta2020
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: arap_development

test:
  <<: *default
  database: arap_test

production:
  <<: *default
  database: arap_production
  username: arap
  password: <%= ENV['ARAP_DATABASE_PASSWORD'] %>
